#!/usr/bin/python

from markov import MarkovChain
import sys

USAGE = "USAGE: {0} word_file\n".format(sys.argv[0])

if len(sys.argv) < 2:
    print USAGE
    sys.exit(1)

filename = sys.argv[1]

chain = MarkovChain()

try:
    with open(filename) as words:
        for word in words:
            # ignore words with non-ascii characters
            try:
                word = word.decode("ascii")
            except UnicodeDecodeError:
                continue
            # prepare the word by adding terminators
            word = "   " + word.strip() + " "
            # generate chain
            for index in range(len(word)-3):
                pair = word[index:index+3]
                n = word[index+3]
                chain.add(pair, n)
except IOError:
    print "Input file does not exist.\n{0}".format(USAGE)
    sys.exit(1)

for _ in range(20):
    w = "   " # three terminators at start
    while(True):
        n = chain.get(w[-3:]) # the state is the last three characters of the string
        if n == " ":
            break
        else:
            w = w + n

    print w.strip() # strip off the terminators
