#!/usr/bin/python

import re
import sys

USAGE = "USAGE: {0} filename\n".format(sys.argv[0])

if len(sys.argv) < 2:
    print USAGE
    sys.exit(1)

filename = sys.argv[1]

r = re.compile("[^a-zA-Z]+")

try:
    with open(filename) as f:
        words = []
        for line in f:
            line = line.strip() # ignore whitespace at the beginning and end of a line
            for word in line.split():
                word = r.sub("", word).lower() # remove all non-ascii characters and case

                if word in words: # only unique words
                    continue

                words.append(word)
except IOError:
    print "File does not exist.\n{0}".format(USAGE)
    sys.exit(1)

words.sort()
for word in words:
    print word
